name: Label Pull Requests

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Fetch labeler.yml from public repo
      uses: actions/download-artifact@v3
      with:
        name: labeler
        path: labeler.yml
        repository: offensive-vk/developer-roadmap
        ref: master

    - name: Label Pull Requests
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        config: labeler.yml